//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalalSamaj.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeSession
    {
        public int SessionId { get; set; }
        public int CommitteeId { get; set; }
        public string SessionCode { get; set; }
        public System.DateTime SessionStartDate { get; set; }
        public System.DateTime SessionEndDate { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsActive { get; set; }
    }
}
