//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalalSamaj.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public int EmployeeId { get; set; }
        public int RefTypeId { get; set; }
        public int SessionId { get; set; }
    }
}
