//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalalSamaj.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public System.DateTime Dob { get; set; }
        public bool IsBoy { get; set; }
        public string Addresse { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
