//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalalSamaj.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Password { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> ForcePasswordChange { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
        public Nullable<int> PasswordCount { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
